function CMSGridEnum() {
   this.SOURCE = "source";
   this.FIELDS = "fields";
   this.VISIBLE_HEAD = "visibleHead";
   this.SORTING = "sorting";
   this.FILTERING = "filtering";
   this.MULTIPLE_FIELD_FILTER = "multipleFieldFilter";
   this.LABEL = "label";
   this.NAME = "name";
   this.TYPE = "type";
   this.LINK = "link",
   this.STYLE = "style",
   this.INT_TYPE = "int";
   this.STRING_TYPE = "string";
   this.DATE_TYPE = "date";
   this.TIME_TYPE = "time";
   this.SORT_ASC = "asc";
   this.SORT_DESC = "desc";
   this.ROW_CLICK = "rowClickable";
   this.ROW_ACTION = "rowAction";
   this.CELL_ACTION = "cellAction";
   this.PAGING = "paging";
   this.HIDE_PAGE_NUMS = "hidePageNumbers";
   this.PER_PAGE = "perPage";
   this.PREV_NEXT = "showPrevNext";
   this.FIRST_LAST = "showFirstLast";
};