BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE Book
	(
	RowId int NOT NULL IDENTITY(1,1) CONSTRAINT PK_Book PRIMARY KEY,
	IdBook int NOT NULL,
	IsActive int NOT NULL,
	IsElectronic int NOT NULL,
	NumOfAvailableCopies int NOT NULL,
	Title nvarchar(255) NOT NULL,
	Author nvarchar(255) NOT NULL,
	PublicationYear int,
	Keywords nvarchar(255),
	BookFilename nvarchar(255),
	MIME nvarchar(255),
	RefCategory int NOT NULL,
	RefLanguage int NOT NULL,
	RefCataloguer int,
	RefUserCreatedBy int,
	DateTimeCreatedOn datetime,
	RefUserDeletedBy int,
	DateTimeDeletedOn datetime
	)  ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IdBook] ON [dbo].[Book]
	(
	[IdBook] ASC	
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF,
	ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS= ON) 
	ON [PRIMARY]
GO
COMMIT