/*
	Table User manipulation.
	Creating table and indexes.
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE Users
	(
	RowId int NOT NULL IDENTITY(1,1) CONSTRAINT PK_User PRIMARY KEY,
	IdUser int NOT NULL,
	IsActive int NOT NULL,
	BirthDate datetime NOT NULL,
	Firstname nvarchar(255) NOT NULL,
	Lastname nvarchar(255) NOT NULL,
	Username nvarchar(255) NOT NULL,
	UserPassword nvarchar(255) NOT NULL,
	Email nvarchar(255) NOT NULL,
	RefRole int NOT NULL,
	RefCategory int,
	RefUserCreatedBy int,
	DateTimeCreatedOn datetime,
	RefUserDeletedBy int,
	DateTimeDeletedOn datetime
	)  ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IdUser] ON [dbo].[Users]
	(
	[IdUser] ASC	
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF,
	ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS= ON) 
	ON [PRIMARY]
GO
COMMIT